dist: trusty
sudo: false
language: ruby
cache: bundler

rvm:
  - 2.4
  - 2.5
  - 2.6

gemfile:
  - spec/gemfiles/rails-5.1.gemfile
  - spec/gemfiles/rails-5.2.gemfile
  - spec/gemfiles/rails-6.0.gemfile

matrix:
  exclude:
    - rvm: 2.4
      gemfile: spec/gemfiles/rails-6.0.gemfile

before_install: gem update bundler
install: bundle install --jobs 3

script:
  - bash -c "if [ '$TRAVIS_RUBY_VERSION' = '2.6' ] && [[ '$BUNDLE_GEMFILE' == *'rails-6.0'* ]]; then bundle exec rubocop --fail-level autocorrect; fi"
  - bundle exec rspec
